### ISSUE TITLE
Property mapping for static values

### ISSUE THREAD

**Issue by joostfarla** [dotwebstack/orchestrate#49]
Sometimes, you want to populate a property value with a static value. This value could be the same for every object instance, but it could also be different. For example a "domain" attribute with a static value, which may differ based on the type of the source root.

**Proposal**

- Introduce a `static` property for a `PropertyMapping` containing 1 or more static values
- For every individual value, optionally provide a matching condition using `ifMatchType`.
- During processing, apply the first value where the matching condition evaluates to `true` or no matching condition is set.
- The `static` and `pathMappings` properties are mutually exclusive.

**Example**

```yaml
objectTypeMappings:
  Bouwwerk:
    sourceRoot:
      - type: bgt:Pand
      - type: bgt:OverigBouwwerk
    propertyMappings:
      identificatie:
        pathMappings:
          path: identificatie
      domein:
        static:
          - value: NL.IMGeo.Pand
            ifMatchType:
              type: oneOf
              options:
                values: 
                  - bgt:Pand
                  - bgt:OverigBouwwerk
          - value: NL.IMXGeo.Bouwwerk
      ...
```

When the value is conditional for a single type, a compact notation could be used:

```yaml
      domein:
        static:
          - value: NL.IMGeo.Pand
            ifMatchType: bgt:Pand
          - value: NL.IMXGeo.Bouwwerk
```
Which is basically the shorthand equivalent for:

```yaml
      domein:
        static:
          - value: NL.IMGeo.Pand
            ifMatchType:
              type: equals
              options:
                value: bgt:Pand
          - value: NL.IMXGeo.Bouwwerk
```

When the value is not conditional, a compact notation could be used:

```yaml
      domein:
        static: NL.IMXGeo.Bouwwerk
```
