### ISSUE TITLE
Non-administrative relations

### ISSUE THREAD

**Issue by joostfarla** [dotwebstack/orchestrate#60]
For example:
* Spatial intersection, x% overlap, etc...
* Foreign keys modelled as flat attributes (e.g. BGT `Pand.identificatieBAGPND`)
  * Optionally map or filter values? e.g. stripping parts or ignoring values like `000000`?

```yaml
sourceRelations:
  - sourceType: bgt:Pand
    property:
      name: gerelateerdBagPand
      target: bag:Pand
      cardinality: 0..1
      inverseName: gerelateerdBgtPand
      inverseCardinality: 0..1
    keyMapping:
      sourcePath: identificatieBAGPND
    filters:
      - property: geometrie
        operator:
          type: intersects
        sourcePath: geometrie2dGrondvlak
```
